/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.danielvrp.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadMedico = new javax.swing.JMenuItem();
        btnCadPaciente = new javax.swing.JMenuItem();
        btnCadConsulta = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();
        btnMenuSobre = new javax.swing.JMenu();
        btnSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CADASTRO");

        menuCadastro.setText("ARQUIVO");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        menuCadMedico.setText("CADASTRAR MEDICO");
        menuCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadMedicoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadMedico);

        btnCadPaciente.setText("CADASTRAR PACIENTE");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(btnCadPaciente);

        btnCadConsulta.setText("CADASTRAR CONSULTA");
        btnCadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadConsultaActionPerformed(evt);
            }
        });
        menuCadastro.add(btnCadConsulta);

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        menuCadastro.add(btnSair);

        jMenuBar1.add(menuCadastro);

        btnMenuSobre.setText("SOBRE");
        btnMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSobreActionPerformed(evt);
            }
        });

        btnSobre.setText("SOBRE");
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });
        btnMenuSobre.add(btnSobre);

        jMenuBar1.add(btnMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadMedicoActionPerformed
        TelaCadMedico telaMed = new TelaCadMedico();
        telaMed.show();
    }//GEN-LAST:event_menuCadMedicoActionPerformed

    private void btnMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSobreActionPerformed
        JOptionPane.showMessageDialog(rootPane, "CRIADO POR DANIEL VICENTE ROCHA PEREIRA");
    }//GEN-LAST:event_btnMenuSobreActionPerformed

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
        TelaCadPaciente telaPac = new TelaCadPaciente();
        telaPac.show();
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnCadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadConsultaActionPerformed
        TelaCadConsulta telaCon = new TelaCadConsulta();
        telaCon.show();
    }//GEN-LAST:event_btnCadConsultaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        JOptionPane.showMessageDialog(rootPane, "CRIADO POR DANIEL VICENTE ROCHA PEREIRA");
    }//GEN-LAST:event_btnSobreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadConsulta;
    private javax.swing.JMenuItem btnCadPaciente;
    private javax.swing.JMenu btnMenuSobre;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenuItem btnSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadMedico;
    private javax.swing.JMenu menuCadastro;
    // End of variables declaration//GEN-END:variables
}
